files:
  - source: /src/main/res/values/strings*.xml
    ignore:
      - /src/main/res/values/strings_not_translatable.xml
      - /src/main/res/values/strings_pref_languages.xml
    translation: /src/main/res/values-%two_letters_code%/%original_file_name%
    translate_attributes: 0
    content_segmentation: 0
